{
 "title": "Oil Extraction",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": "select name from oil_well_data group by name limit 100;"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\nflowRate,\nwellheadTemperature,\noilPressure,\ncasingPressure,\nbackPressure,\nvoltage,\ncurrent\nFROM iot_data.oil_well_data ORDER BY id desc limit 1;"
    }
   ]
  },
  {
   "title": "Status history",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT \n  wellheadTemperature,\n  voltage,\n  current,\n  flowRate,\n  timestamp\nFROM iot_data.oil_well_data \n  WHERE name = '$name' and timestamp between $__timeFrom()  and $__timeTo()"
    }
   ]
  },
  {
   "title": "Pressure history",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pressurepa" } },
   "targets": [
    {
     "rawSql": "SELECT \n  oilPressure,\n  casingPressure,\n  backPressure,\n  timestamp\nFROM iot_data.oil_well_data \n  WHERE name = '$name' and timestamp between $__timeFrom()  and $__timeTo()"
    }
   ]
  },
  {
   "title": "Oil Well events log",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "targets": [
    {
     "dataset": "iot_data",
     "rawSql": "SELECT\n\nclientid,\nevent,\ncreated_at\n\n FROM iot_data.oil_well_events\n\n  ORDER BY id desc LIMIT 10"
    }
   ]
  }
 ]
}